"""Experimental score fusion, not calibrated probabilities.

Missing ML evidence produces an inconclusive result. Metadata and visual
heuristics alone cannot establish image origin or distinguish editing methods.
"""

import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

VERDICT_LABELS: Dict[str, str] = {
    "ai_generated":     "AI Generated",
    "ai_edited":        "AI Edited",
    "traditional_edit": "Traditionally Edited",
    "authentic":        "Authentic / Original",
    "inconclusive":     "Inconclusive",
}

EXPLANATIONS: Dict[str, str] = {
    "ai_generated": (
        "Multiple detectors indicate this content was fully generated by an AI model "
        "(GAN, diffusion model, or similar)."
    ),
    "ai_edited": (
        "Evidence suggests portions of this content were modified using AI-powered "
        "editing tools."
    ),
    "traditional_edit": (
        "Analysis indicates traditional image editing (Photoshop, Lightroom, etc.) "
        "was applied."
    ),
    "authentic": (
        "No significant manipulation signals detected. The content appears to be an "
        "original, unedited capture."
    ),
    "inconclusive": (
        "Insufficient data to determine authenticity. The AI detection models were "
        "unavailable during this analysis. Metadata and visual heuristics cannot "
        "establish origin on their own. Retry when the models are available. "
        "Missing metadata does not indicate AI generation."
    ),
}


def _clamp(v: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, v))


class ConfidenceAggregator:
    def aggregate(
        self,
        deepfake: Dict[str, Any],
        gan: Dict[str, Any],
        manipulation: Dict[str, Any],
        metadata: Dict[str, Any],
        statistical: Optional[float] = None,
    ) -> Dict[str, Any]:
        """
        Aggregate available signals into experimental category scores.

        Parameters
        ----------
        deepfake    : DeepfakeDetector result (includes api_success flag)
        gan         : GANDetector result (includes api_success flag)
        manipulation: ManipulationLocalizer result
        metadata    : MetadataAnalyzer result
        statistical : Optional ai_likelihood_score from statistical analysis [0,1]
        """
        # ── Extract raw scores ────────────────────────────────────────────────
        df_score:   float = _clamp(deepfake.get("score", 0.0))
        gan_score:  float = _clamp(gan.get("score", 0.0))
        manip_score: float = _clamp(manipulation.get("score", 0.0))
        meta_score:  float = _clamp(metadata.get("anomaly_score", 0.0))
        stat_score:  float = _clamp(statistical if statistical is not None else manipulation.get("ai_likelihood_score", 0.0))

        # ── Determine ML availability ─────────────────────────────────────────
        # api_success=True  → model ran and returned a genuine score
        # api_success=False → timeout / error / disabled → treat as missing data
        api_success_df  = deepfake.get("api_success", False)
        api_success_gan = gan.get("api_success", False)
        ml_available    = api_success_df or api_success_gan

        # Legacy: detectors without api_success field — fall back to weights_available
        if "api_success" not in deepfake and deepfake.get("weights_available"):
            ml_available = True
            api_success_df = True
        if "api_success" not in gan and gan.get("weights_available"):
            ml_available = True
            api_success_gan = True

        # ── M1: Inconclusive verdict ──────────────────────────────────────────
        # Heuristics and editable metadata alone cannot establish origin.
        df_score = df_score if api_success_df else 0.0
        gan_score = gan_score if api_success_gan else 0.0
        if not ml_available:
            return {
                "ai_generated":    0.0,
                "ai_edited":       0.0,
                "traditional_edit": 0.0,
                "authentic":       0.0,
                "verdict":         VERDICT_LABELS["inconclusive"],
                "verdict_key":     "inconclusive",
                "confidence":      0.0,
                "explanation":     EXPLANATIONS["inconclusive"],
                "limited_mode":    True,
                "ml_available":    False,
            }

        # ── Mode A: ML signals available ──────────────────────────────────────
        ai_generated = 0.35 * df_score + 0.30 * gan_score + 0.20 * meta_score + 0.15 * stat_score
        ai_edited = 0.30 * manip_score + 0.15 * df_score + 0.10 * meta_score
        traditional_edit = 0.40 * manip_score + 0.10 * meta_score
        confidence_cap = 0.97

        ai_generated    = _clamp(ai_generated)
        ai_edited       = _clamp(ai_edited)
        traditional_edit = _clamp(traditional_edit)

        authentic = _clamp(1.0 - (ai_generated + ai_edited + traditional_edit))

        # Normalise to sum = 1.0
        total = ai_generated + ai_edited + traditional_edit + authentic + 1e-8
        ai_generated    /= total
        ai_edited       /= total
        traditional_edit /= total
        authentic       /= total

        # ── Verdict = argmax ──────────────────────────────────────────────────
        scores: Dict[str, float] = {
            "ai_generated":    ai_generated,
            "ai_edited":       ai_edited,
            "traditional_edit": traditional_edit,
            "authentic":       authentic,
        }
        verdict_key: str = max(scores, key=scores.get)  # type: ignore[arg-type]
        confidence: float = min(scores[verdict_key], confidence_cap)

        # ── limited_mode flag (UI banner) ─────────────────────────────────────
        # Show banner ONLY when BOTH ML detectors had api_success=False
        limited_mode = not ml_available

        explanation = EXPLANATIONS[verdict_key]

        return {
            "ai_generated":    round(ai_generated, 4),
            "ai_edited":       round(ai_edited, 4),
            "traditional_edit": round(traditional_edit, 4),
            "authentic":       round(authentic, 4),
            "verdict":         VERDICT_LABELS[verdict_key],
            "verdict_key":     verdict_key,
            "confidence":      round(confidence, 4),
            "explanation":     explanation,
            "limited_mode":    limited_mode,
            "ml_available":    ml_available,
        }

    def aggregate_video(self, frame_results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Aggregate per-frame results to video-level verdict (temporal mean)."""
        if not frame_results:
            return self.aggregate({}, {}, {}, {})

        usable_frames = [
            frame for frame in frame_results
            if frame.get("ml_available") is True
            and frame.get("final_verdict") != VERDICT_LABELS["inconclusive"]
        ]
        if not usable_frames:
            return self.aggregate({}, {}, {}, {})
        partial = len(usable_frames) != len(frame_results)

        keys: List[str] = [
            "ai_generated_probability",
            "ai_edited_probability",
            "traditional_edit_probability",
            "authentic_probability",
        ]

        averages: Dict[str, float] = {}
        for k in keys:
            vals: List[float] = [f.get(k, 0.0) for f in usable_frames]
            averages[k] = sum(vals) / len(vals)

        total: float = sum(averages.values())
        if total <= 0:
            return self.aggregate({}, {}, {}, {})
        ai_gen  = averages["ai_generated_probability"] / total
        ai_edit = averages["ai_edited_probability"] / total
        trad    = averages["traditional_edit_probability"] / total
        auth    = averages["authentic_probability"] / total

        scores: Dict[str, float] = {
            "ai_generated":    ai_gen,
            "ai_edited":       ai_edit,
            "traditional_edit": trad,
            "authentic":       auth,
        }
        verdict_key: str = max(scores, key=scores.get)  # type: ignore[arg-type]

        return {
            "ai_generated":    round(ai_gen, 4),
            "ai_edited":       round(ai_edit, 4),
            "traditional_edit": round(trad, 4),
            "authentic":       round(auth, 4),
            "verdict":         VERDICT_LABELS[verdict_key],
            "verdict_key":     verdict_key,
            "confidence":      round(min(scores[verdict_key], 0.65 if partial else 0.97), 4),
            "explanation":     EXPLANATIONS[verdict_key] + (
                " Some sampled frames were inconclusive; this result covers only usable frames."
                if partial else ""
            ),
            "limited_mode":    partial,
            "ml_available":    True,
        }
