"""
ConfidenceAggregator — Fuses signals from all detectors into a final verdict.

TWO-MODE WEIGHT SYSTEM
======================

Mode A — ML Available (api_success=True for at least one ML detector):
  ai_generated = 0.35×deepfake + 0.30×gan + 0.20×metadata + 0.15×statistical
  ai_edited    = 0.30×manipulation + 0.15×deepfake + 0.10×metadata
  traditional  = 0.40×manipulation + 0.10×metadata
  authentic    = complement (normalised)

Mode B — ML Unavailable (both api_success=False or both detectors disabled):
  ai_generated = 0.55×metadata + 0.30×statistical + 0.15×manipulation
  ai_edited    = 0.25×manipulation + 0.20×metadata
  traditional  = 0.35×manipulation + 0.10×metadata
  authentic    = complement, capped at 0.65 max
  ALL verdict confidence capped at 0.65

Inconclusive Verdict (M1 — Mandatory):
  Triggered when: Mode B AND metadata_anomaly_score < 0.35
  Returns verdict="Inconclusive" — system declines to guess rather than
  falsely report "Authentic / Original" when evidence is insufficient.

Root cause this fixes:
  Previous: deepfake=0, gan=0 (API failed/face-only model) → authentic=77%
  Fixed:    api_success=False detected → Mode B → metadata dominates →
            "Inconclusive" if signals too weak, else uses metadata score
"""

import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

VERDICT_LABELS: Dict[str, str] = {
    "ai_generated":     "AI Generated",
    "ai_edited":        "AI Edited",
    "traditional_edit": "Traditionally Edited",
    "authentic":        "Authentic / Original",
    "inconclusive":     "Inconclusive",
}

EXPLANATIONS: Dict[str, str] = {
    "ai_generated": (
        "Multiple detectors indicate this content was fully generated by an AI model "
        "(GAN, diffusion model, or similar)."
    ),
    "ai_edited": (
        "Evidence suggests portions of this content were modified using AI-powered "
        "editing tools."
    ),
    "traditional_edit": (
        "Analysis indicates traditional image editing (Photoshop, Lightroom, etc.) "
        "was applied."
    ),
    "authentic": (
        "No significant manipulation signals detected. The content appears to be an "
        "original, unedited capture."
    ),
    "inconclusive": (
        "Insufficient data to determine authenticity. The AI detection models were "
        "unavailable during this analysis and the metadata signals are too weak to "
        "reach a reliable verdict. Try again in a few moments or upload a JPEG "
        "photograph with camera EXIF data for a fuller analysis."
    ),
}


def _clamp(v: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, v))


class ConfidenceAggregator:
    def aggregate(
        self,
        deepfake: Dict[str, Any],
        gan: Dict[str, Any],
        manipulation: Dict[str, Any],
        metadata: Dict[str, Any],
        statistical: Optional[float] = None,
    ) -> Dict[str, Any]:
        """
        Aggregate all detector signals into a final probability matrix.

        Parameters
        ----------
        deepfake    : DeepfakeDetector result (includes api_success flag)
        gan         : GANDetector result (includes api_success flag)
        manipulation: ManipulationLocalizer result
        metadata    : MetadataAnalyzer result
        statistical : Optional ai_likelihood_score from statistical analysis [0,1]
        """
        # ── Extract raw scores ────────────────────────────────────────────────
        df_score:   float = _clamp(deepfake.get("score", 0.0))
        gan_score:  float = _clamp(gan.get("score", 0.0))
        manip_score: float = _clamp(manipulation.get("score", 0.0))
        meta_score:  float = _clamp(metadata.get("anomaly_score", 0.0))
        stat_score:  float = _clamp(statistical or manipulation.get("ai_likelihood_score", 0.0))

        # ── Determine ML availability ─────────────────────────────────────────
        # api_success=True  → model ran and returned a genuine score
        # api_success=False → timeout / error / disabled → treat as missing data
        api_success_df  = deepfake.get("api_success", False)
        api_success_gan = gan.get("api_success", False)
        ml_available    = api_success_df or api_success_gan

        # Legacy: detectors without api_success field — fall back to weights_available
        if not deepfake.get("api_success") and deepfake.get("weights_available") and df_score > 0:
            ml_available = True
            api_success_df = True
        if not gan.get("api_success") and gan.get("weights_available") and gan_score > 0:
            ml_available = True
            api_success_gan = True

        # ── M1: Inconclusive verdict ──────────────────────────────────────────
        # When no ML data AND metadata is too weak to make a determination.
        if not ml_available and meta_score < 0.35 and stat_score < 0.30:
            return {
                "ai_generated":    0.0,
                "ai_edited":       0.0,
                "traditional_edit": 0.0,
                "authentic":       0.0,
                "verdict":         VERDICT_LABELS["inconclusive"],
                "verdict_key":     "inconclusive",
                "confidence":      0.0,
                "explanation":     EXPLANATIONS["inconclusive"],
                "limited_mode":    True,
                "ml_available":    False,
            }

        # ── Mode A: ML signals available ──────────────────────────────────────
        if ml_available:
            ai_generated    = 0.35 * df_score + 0.30 * gan_score + 0.20 * meta_score + 0.15 * stat_score
            ai_edited       = 0.30 * manip_score + 0.15 * df_score + 0.10 * meta_score
            traditional_edit = 0.40 * manip_score + 0.10 * meta_score
            mode_label = "ml_available"
            confidence_cap  = 0.97   # allow high confidence when ML ran
        else:
            # ── Mode B: No ML signals — metadata + statistical dominant ───────
            ai_generated    = 0.55 * meta_score + 0.30 * stat_score + 0.15 * manip_score
            ai_edited       = 0.25 * manip_score + 0.20 * meta_score
            traditional_edit = 0.35 * manip_score + 0.10 * meta_score
            mode_label = "metadata_only"
            confidence_cap  = 0.65   # cap ALL verdicts — insufficient data

        # ── Clamp, compute authentic, normalise ───────────────────────────────
        ai_generated    = _clamp(ai_generated)
        ai_edited       = _clamp(ai_edited)
        traditional_edit = _clamp(traditional_edit)

        # Mode B: authentic is capped — we don't let "no signal" → "definitely authentic"
        if not ml_available:
            authentic = _clamp(1.0 - (ai_generated + ai_edited + traditional_edit), 0.0, 0.65)
        else:
            authentic = _clamp(1.0 - (ai_generated + ai_edited + traditional_edit))

        # Normalise to sum = 1.0
        total = ai_generated + ai_edited + traditional_edit + authentic + 1e-8
        ai_generated    /= total
        ai_edited       /= total
        traditional_edit /= total
        authentic       /= total

        # ── Verdict = argmax ──────────────────────────────────────────────────
        scores: Dict[str, float] = {
            "ai_generated":    ai_generated,
            "ai_edited":       ai_edited,
            "traditional_edit": traditional_edit,
            "authentic":       authentic,
        }
        verdict_key: str = max(scores, key=scores.get)  # type: ignore[arg-type]
        confidence: float = min(scores[verdict_key], confidence_cap)

        # ── limited_mode flag (UI banner) ─────────────────────────────────────
        # Show banner ONLY when BOTH ML detectors had api_success=False
        limited_mode = not ml_available

        explanation = EXPLANATIONS[verdict_key]
        if limited_mode:
            explanation = (
                f"{explanation} "
                "[Note: AI/GAN detectors were unavailable — result is based on "
                "metadata forensics and statistical image analysis only.]"
            )

        return {
            "ai_generated":    round(ai_generated, 4),
            "ai_edited":       round(ai_edited, 4),
            "traditional_edit": round(traditional_edit, 4),
            "authentic":       round(authentic, 4),
            "verdict":         VERDICT_LABELS[verdict_key],
            "verdict_key":     verdict_key,
            "confidence":      round(confidence, 4),
            "explanation":     explanation,
            "limited_mode":    limited_mode,
            "ml_available":    ml_available,
        }

    def aggregate_video(self, frame_results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Aggregate per-frame results to video-level verdict (temporal mean)."""
        if not frame_results:
            return self.aggregate({}, {}, {}, {})

        keys: List[str] = [
            "ai_generated_probability",
            "ai_edited_probability",
            "traditional_edit_probability",
            "authentic_probability",
        ]

        averages: Dict[str, float] = {}
        for k in keys:
            vals: List[float] = [f.get(k, 0.0) for f in frame_results]
            averages[k] = sum(vals) / len(vals)

        total: float = sum(averages.values()) + 1e-8
        ai_gen  = averages["ai_generated_probability"] / total
        ai_edit = averages["ai_edited_probability"] / total
        trad    = averages["traditional_edit_probability"] / total
        auth    = averages["authentic_probability"] / total

        scores: Dict[str, float] = {
            "ai_generated":    ai_gen,
            "ai_edited":       ai_edit,
            "traditional_edit": trad,
            "authentic":       auth,
        }
        verdict_key: str = max(scores, key=scores.get)  # type: ignore[arg-type]

        return {
            "ai_generated":    round(ai_gen, 4),
            "ai_edited":       round(ai_edit, 4),
            "traditional_edit": round(trad, 4),
            "authentic":       round(auth, 4),
            "verdict":         VERDICT_LABELS[verdict_key],
            "verdict_key":     verdict_key,
            "confidence":      round(scores[verdict_key], 4),
            "explanation":     EXPLANATIONS[verdict_key],
            "limited_mode":    False,
            "ml_available":    True,
        }
