"""
ConfidenceAggregator — fuses signals from all detectors into a final verdict.

Signal weights (tuned empirically):
  deepfake    → ai_generated (0.40)
  gan         → ai_generated (0.35)
  manipulation → ai_edited / traditional_edit (0.35)
  metadata    → boosts/suppresses all categories (0.20)
"""

import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

VERDICT_LABELS = {
    "ai_generated": "AI Generated",
    "ai_edited": "AI Edited",
    "traditional_edit": "Traditionally Edited",
    "authentic": "Authentic / Original",
}

EXPLANATIONS = {
    "ai_generated": "Multiple detectors indicate this content was fully generated by an AI model (GAN, diffusion model, or similar).",
    "ai_edited": "Evidence suggests portions of this content were modified using AI-powered editing tools.",
    "traditional_edit": "Analysis indicates traditional image editing (Photoshop, Lightroom, etc.) was applied.",
    "authentic": "No significant manipulation signals detected. The content appears to be an original, unedited capture.",
}


class ConfidenceAggregator:
    def aggregate(
        self,
        deepfake: Dict[str, Any],
        gan: Dict[str, Any],
        manipulation: Dict[str, Any],
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Aggregate detector scores into a final probability matrix."""

        df_score = deepfake.get("score", 0.0)
        gan_score = gan.get("score", 0.0)
        manip_score = manipulation.get("score", 0.0)
        meta_score = metadata.get("anomaly_score", 0.0)

        # ── Base probabilities ────────────────────────────────────────────────
        ai_generated = 0.40 * df_score + 0.35 * gan_score + 0.15 * meta_score
        ai_edited = 0.50 * manip_score + 0.20 * (df_score * 0.3) + 0.15 * meta_score
        traditional_edit = 0.45 * manip_score + 0.10 * meta_score
        authentic = 1.0 - max(ai_generated, ai_edited, traditional_edit)

        # Clamp
        ai_generated = min(max(ai_generated, 0.0), 1.0)
        ai_edited = min(max(ai_edited, 0.0), 1.0)
        traditional_edit = min(max(traditional_edit, 0.0), 1.0)
        authentic = min(max(authentic, 0.0), 1.0)

        # ── Normalise to sum=1 ────────────────────────────────────────────────
        total = ai_generated + ai_edited + traditional_edit + authentic + 1e-8
        ai_generated /= total
        ai_edited /= total
        traditional_edit /= total
        authentic /= total

        # ── Verdict = argmax ──────────────────────────────────────────────────
        scores = {
            "ai_generated": ai_generated,
            "ai_edited": ai_edited,
            "traditional_edit": traditional_edit,
            "authentic": authentic,
        }
        verdict_key = max(scores, key=scores.get)
        confidence = scores[verdict_key]

        return {
            "ai_generated": round(ai_generated, 4),
            "ai_edited": round(ai_edited, 4),
            "traditional_edit": round(traditional_edit, 4),
            "authentic": round(authentic, 4),
            "verdict": VERDICT_LABELS[verdict_key],
            "verdict_key": verdict_key,
            "confidence": round(confidence, 4),
            "explanation": EXPLANATIONS[verdict_key],
        }

    def aggregate_video(self, frame_results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Aggregate per-frame results to video-level verdict (temporal mean)."""
        if not frame_results:
            return self.aggregate({}, {}, {}, {})

        keys = ["ai_generated_probability", "ai_edited_probability",
                "traditional_edit_probability", "authentic_probability"]

        averages = {}
        for k in keys:
            vals = [f.get(k, 0.0) for f in frame_results]
            averages[k] = sum(vals) / len(vals)

        # Renormalise
        total = sum(averages.values()) + 1e-8
        ai_gen = averages["ai_generated_probability"] / total
        ai_edit = averages["ai_edited_probability"] / total
        trad = averages["traditional_edit_probability"] / total
        auth = averages["authentic_probability"] / total

        scores = {
            "ai_generated": ai_gen,
            "ai_edited": ai_edit,
            "traditional_edit": trad,
            "authentic": auth,
        }
        verdict_key = max(scores, key=scores.get)
        confidence = scores[verdict_key]

        return {
            "ai_generated": round(ai_gen, 4),
            "ai_edited": round(ai_edit, 4),
            "traditional_edit": round(trad, 4),
            "authentic": round(auth, 4),
            "verdict": VERDICT_LABELS[verdict_key],
            "verdict_key": verdict_key,
            "confidence": round(confidence, 4),
            "explanation": EXPLANATIONS[verdict_key],
        }
