"""
GANDetector — CNN-based GAN-generated image detector.

Based on CNNDetect (Wang et al., 2020).
Detects images generated by GANs (StyleGAN, BigGAN, etc.).
"""

import logging
from typing import Dict, Any

import torch
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms

logger = logging.getLogger(__name__)

GAN_TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])


class GANDetector:
    def __init__(self, model_loader):
        self.model = model_loader.get_model("gan_detect")
        self.device = model_loader.device

    def predict(self, image_path: str) -> Dict[str, Any]:
        """
        Returns:
            score: float in [0, 1] — probability of being GAN-generated
            label: 'gan' or 'real'
        """
        try:
            img = Image.open(image_path).convert("RGB")
            tensor = GAN_TRANSFORM(img).unsqueeze(0).to(self.device)

            with torch.no_grad():
                logit = self.model(tensor)
                prob = torch.sigmoid(logit).item()

            return {
                "score": float(prob),
                "label": "gan" if prob > 0.5 else "real",
                "confidence": float(max(prob, 1 - prob)),
            }
        except Exception as e:
            logger.warning(f"GAN detection failed: {e}")
            return {"score": 0.0, "label": "unknown", "confidence": 0.0}
